import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Preloader from "@/components/Preloader";
import { gsap } from "gsap";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";

const Home = () => {
  const router = useRouter();
  const toAbout = () => {
    router.push("/about");
  };
  const toContact = () => {
    router.push("/contact");
  };

  return (
    <React.Suspense fallback={Preloader}>
      <div className="component">
        <Head>
          <title>Lakira Minlaka</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <div className={styles.section}>
          <div className={styles.textContainer}>
            <h1 className={styles.welcomheading}>
              Building the Future, One Line of Code at a Time
            </h1>
            <p className={styles.welcomepara}>
              Hey I’m Lakira Minlaka, Welcome to my Website!
            </p>
            <div className={styles.btns}>
              <button className={styles.btn1} onClick={toAbout}>
                Get to know me
              </button>
              <button className={styles.btn2} onClick={toContact}>
                Say Hello
              </button>
            </div>
          </div>
          <div className={styles.imageContainer}>
            <img src="./Home1.png" alt="Image" />
          </div>
        </div>
        {/* section two */}
        <div className={styles.section}>
          <h1 className={styles.headingmobile}>About Me</h1>

          <div className={`${styles.imageContainer} ${styles.aboutImg}`}>
            <img src="./Home2.png" alt="about" />
          </div>
          <div className={`${styles.textContainer} ${styles.about}`}>
            <h1 className={styles.heading}>About Me</h1>
            <p className={styles.aboutpara}>
              Meet Lakira Minlaka, a 17-year-old programmer with a passion for
              innovation. As a student and coding enthusiast, she is constantly
              pushing the limits of what's possible and making a positive impact
              through her work. Explore her portfolio to see her skills and get
              a glimpse into the mind of this rising tech star.
            </p>
            <button className={styles.btn1} onClick={toAbout}>
              Find out more
            </button>
          </div>
        </div>
        <div className={styles.section}>
          <div className={styles.textContainer}>
            <h1 className={styles.heading}>Get in touch</h1>
            <p className={styles.aboutpara}>
              I'd love to hear from you! Please feel free to reach out with any
              questions or comments.
            </p>
            <button className={styles.btn1} onClick={toContact}>
              Let’s get Connect
            </button>
          </div>
          <div className={styles.imageContainer}>
            <img src="./Home3.png" alt="contact" />
          </div>
        </div>
        <Footer />
      </div>
    </React.Suspense>
  );
};

export default Home;
